"""Changes models fields

Revision ID: ae5e4215a9ea
Revises: f1823ece7c39
Create Date: 2024-02-11 16:07:03.354831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5e4215a9ea'
down_revision = 'f1823ece7c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
